language: ruby
rvm: 2.1.1
install: gem install kwalify
before_install: wget https://loot.github.io/masterlist.schema.yaml
script:
  ### Check for basic coding style, but failure here won't fail the build.
  - 'grep --line-number --perl-regexp "name: (?!(''|-?(Delev|Relev|Deactivate|NoMerge)$))" masterlist.yaml || true'
  ### Check masterlist against the Kwalify schema
  # The `return` addition is a hack as `kwalify` doesn't return with a
  # non-zero exist code when the "kwalification" fails, so this forces an
  # error if anything fails the validation.
  - kwalify -f masterlist.schema.yaml masterlist.yaml && return $(kwalify -q -f masterlist.schema.yaml masterlist.yaml|wc -l)

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
